In [25]:
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine

conn = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = 'Krishna'
)

cursor = conn.cursor()
print("Connected to Mysql")

cursor.execute("CREATE DATABASE IF NOT EXISTS sales_project")
cursor.execute("USE sales_project")
print("Database Created")

engine = create_engine('mysql+mysqlconnector://root:Krishna@localhost/sales_project')
df= pd.read_csv('superstore_clean.csv')
df.to_sql('superstore', con = engine, if_exists= 'replace', index = False)

print("Data Loaded : Rows",len(df))

def run_query(query):
    return pd.read_sql(query,engine)

q1 = run_query("""SELECT Category, ROUND(SUM(profit),2) AS Total_profit, 
               ROUND(SUm(Sales),2) AS Total_Sales 
               FROM superstore
               GROUP BY Category 
               ORDER BY total_Profit 
               DESC""")

print("profit by category")
q1


q2 = run_query(""" SELECT `Product Name`, ROUND(SUM(profit),2) AS total_profit,
               ROUND(SUM(sales),2) AS total_sales 
               FROM superstore 
               GROUP BY `product name` 
               HAVING SUM(Profit) < 0
               ORDER  BY total_sales 
               DESC """)
print("High Sales but loss making producsts")
display(q2)


q3 =  run_query(""" SELECT State, ROUND(SUM(profit),2)AS total_profit, 
                ROUND(SUM(sales),2)AS total_sales 
                FROM superstore GROUP BY state 
                ORDER BY total_profit 
                DESC """)
print("top 10 Profitable states")
q3.head(10)


q4 = run_query(""" SELECT Segment, ROUND(SUM(sales),2) AS total_Sales,
               ROUND(SUM(Profit), 2) AS total_profit,
               COUNT(DISTINCT `Order ID`) AS total_orders
               FROM superstore 
               GROUP BY Segment 
               ORDER BY total_sales
               desc""")
print("Sales as per segment")
q4


q5 = run_query (""" SELECT `Ship Mode`, ROUND(AVG(`Shipping Days`),1) AS avg_shipping_days, 
                COUNT(*)AS total_orders 
                FROM superstore 
                GROUP BY `Ship Mode`
                ORDER BY avg_shipping_days 
                ASC""")
print("Average Shpping days by ship mode")
q5

q6 = run_query(""" SELECT `Order year`, `Order month`, ROUND(SUM(sales),2)AS total_sales, ROUND(SUM(profit),2)AS total_profit 
               FROM superstore
               GROUP BY `Order year`, `Order month`
               ORDER BY `Order year`, `Order month` """)
print("Sales and profit by month and year")
q6


q7 = run_query("""SELECT `Customer Name`, ROUND(SUM(sales),2)AS total_sales,ROUND(SUM(profit),2)AS total_profit FROM superstore
               GROUP BY `Customer Name`
               ORDER BY total_profit DESC
               limit 10 """)

print("Top 10 customers by profit")
q7

q8= run_query("""SELECT `Product Name`,ROUND(AVG(Discount),2)AS avg_discount, ROUND(SUM(Sales), 2) AS Total_Sales, ROUND(AVG(`Profit Margin %`),2)AS avg_margin,
              ROUND(SUM(Profit),2)AS Total_profit
              FROM superstore
              GROUP BY `Product Name`
              HAVING avg_discount >0.4
              ORDER BY Total_profit DESC
              limit 10 """)

print("Products with high discount and profit")
q8

q9 = run_query("""SELECT `Sub-Category`, ROUND(SUM(sales),2)AS total_sales, ROUND(SUM(profit),2)AS total_profit, ROUND(AVG(`Profit Margin %`),2)AS avg_margin
               FROM superstore
               GROUP BY `Sub-Category`
               ORDER BY avg_margin DESC """)
print("Profit margin by sub category")
q9

Connected to Mysql
Database Created
Data Loaded : Rows 9994
profit by category
High Sales but loss making producsts

,Product Name,total_profit,total_sales
0,Cisco TelePresence System EX90 Videoconferenci...,-1811.08,22638.48
1,GBC DocuBind P400 Electric Binding System,-1878.17,17965.07
2,High Speed Automatic Electric Letter Opener,-262.00,17030.31
3,Lexmark MX611dhe Monochrome Laser Printer,-4589.97,16829.90
4,Martin Yale Chadless Opener Electric Letter Op...,-1299.18,16656.20
...,...,...,...
296,Acco Economy Flexible Poly Round Ring Binder,-5.74,11.48
297,Computer Printout Index Tabs,-2.02,11.09
298,Storex Flexible Poly Binders with Double Pockets,-2.01,10.82
299,PNY Rapid USB Car Charger - Black,-2.08,9.59
300,Eureka Disposable Bags for Sanitaire Vibra Gro...,-4.47,1.62

top 10 Profitable states
Sales as per segment
Average Shpping days by ship mode
Sales and profit by month and year
Top 10 customers by profit
Products with high discount and profit
Profit margin by sub category

   Sub-Category  total_sales  total_profit  avg_margin
0        Labels     12486.31       5546.25       42.97
1         Paper     78479.21      34053.57       42.56
2     Envelopes     16476.40       6964.18       42.31
3       Copiers    149528.03      55617.82       31.72
4     Fasteners      3024.28        949.52       29.92
5           Art     27118.79       6527.79       25.16
6   Accessories    167380.32      41936.64       21.82
7   Furnishings     91705.16      13059.14       13.71
8        Phones    330007.05      44515.73       11.92
9      Supplies     46673.54      -1189.10       11.20
10      Storage    223843.61      21278.83        8.91
11       Chairs    328449.10      26590.17        4.39
12     Machines    189238.63       3384.76       -7.20
13    Bookcases    114880.00      -3472.56      -12.66
14       Tables    206965.53     -17725.48      -14.77
15   Appliances    107532.16      18138.01      -15.69
16      Binders    203412.73      30221.76      -19.96